theme = "lynx"
title = "Lynx"

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[author]
  name = "Lynx"
  headline = "A simple links theme for Hugo built with Tailwind CSS"
  image = "author.jpg"
  links = [
    { link = { href = "https://github.com/jpanther/lynx/blob/stable/README.md", text = "View the readme", icon = "github" } },
    { link = { href = "styles/", text = "All the link styles", target = "_self" } },
    { github = "https://github.com/jpanther/lynx" },
    { twitter = "https://twitter.com/jpanther" },
    { font-awesome = { href = "https://fontawesome.com/", text = "FontAwesome" } },
  ]

[markup.highlight]
  noClasses = false

[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true
